### ISSUE TITLE
Compress artifacts in graphics tests in CI

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#145]
If graphics tests are failed then you can only download file-by-file and if [there is a lot of failing test cases](https://circleci.com/gh/tradingview/lightweight-charts/3086#artifacts/containers/0) it takes some time.

Needs to compress the whole folder into one archive and store it as artifact besides with cmp folder.

https://circleci.com/docs/2.0/artifacts/#uploading-artifacts

https://support.circleci.com/hc/en-us/articles/360024275534?input_string=store_artifacts+step

**Comment by timocov** [comment]
It could be something like the following:

```yml
      - run: scripts/run-graphics-tests.sh
      - run:
          name: "Generate archive with screenshots"
          command: |
            tar -czvf ./screenshots.tar.gz graphics-cmp-data/
            mv ./screenshots.tar.gz ./graphics-cmp-data/screenshots.tar.gz
```

But we need to run it in a case of failed tests (currently, if we add this to CI config right after running tests, it won't run due failed previous step).
